Gui:
    Game Name: "J League Winning Eleven 2009 - SLPM_551.82"

Game Data:
    Base Address: 1046528
    Total Stadiums: 55
    Stadium Name Lenght : 73
    Total Leagues: 39
    Total Teams: 278
    Total Nationalities: 138

SLXX Offsets:
    Teams Offsets Table: 3193424
    Teams Text Data Offset : 3182864
    Teams Text Data Size: 10032

    Nationalities Offsets Table: 3202256
    Nationalities Text Data Offset: 3198144
    Nationalities Text Data Size: 4112

OVER Offsets:
    Stadiums Offsets Table 1: 1002384
    Stadiums Offsets Table 2: 2211536
    Leagues Offsets Table 1: 1006528
    Leagues Offsets Table 2: 2215680

Callnames:
    Name Lenght: 40
    Encoding: "cp932"
