Gui:
    Game Name: "J League Winning Eleven 2009 - SLPM_551.82"

Game Data:
    Base Address: 1046528
    Total Stadiums: 55
    Stadium Name Lenght : 73
    Total Leagues: 39
    Total Teams: 270

SLXX Offsets:
    Teams Offsets Table: 3193424
    Teams Table Size: 4720
    Teams Text Data Size: 9648
    Nationalities Offsets Table: 3202256
    Nationalities Table Size: 1104

OVER Offsets:
    Stadiums Offsets Table 1: 1002384
    Stadiums Offsets Table 2: 2211536
    Leagues Offsets Table 1: 1006528
    Leagues Offsets Table 2: 2215680

Callnames:
    Name Lenght: 40
    Encoding: "cp932"
