Gui:
    Game Name: "Pro Evolution Soccer 2008 - SLES_549.13"

Game Data:
    Base Address: 1046528
    Total Stadiums: 35
    Stadium Name Lenght : 61
    Total Leagues: 11
    Total Teams: 320
    Total Nationalities: 122

SLXX Offsets:
    Teams Offsets Table: 3161904
    Teams Text Data Offset : 3153576
    Teams Text Data Size: 8072

    Nationalities Offsets Table: 3169872
    Nationalities Text Data Offset: 3167200
    Nationalities Text Data Size: 2672

OVER Offsets:
    Stadiums Offsets Table 1: 1192128
    Stadiums Offsets Table 2: 2428656
    Leagues Offsets Table 1: 1194368
    Leagues Offsets Table 2: 2430896

Callnames:
    Name Lenght: 48
    Encoding: "utf8"
