Gui:
    Game Name: "Pro Evolution Soccer 5 (Italy) - SLES_535.45"

Game Data:
    Base Address: 1046528
    Total Stadiums: 35
    Stadium Name Lenght : 61
    Total Leagues: 11
    Total Teams: 233
    Total Nationalities: 111

SLXX Offsets:
    Teams Offsets Table: 2782592
    Teams Text Data Offset : 2776640
    Teams Text Data Size: 5696

    Nationalities Offsets Table: 2788976
    Nationalities Text Data Offset: 2786496
    Nationalities Text Data Size: 2480

OVER Offsets:
    Stadiums Offsets Table 1: 647840
    Stadiums Offsets Table 2: 1888096
    Leagues Offsets Table 1: 650016
    Leagues Offsets Table 2: 1890272

Callnames:
    Name Lenght: 48
    Encoding: "utf8"
