Gui:
    Game Name: "Pro Evolution Soccer 5 PC"

Game Data:
    Base Address: 0x400000
    Total Stadiums: 35
    Stadium Name Lenght : 61
    Total Leagues: 11
    Total Teams: 233
    Total Nationalities: 111

SLXX Offsets:
    Teams Offsets Table: 0
    Teams Text Data Offset : 0
    Teams Text Data Size: 0

    Nationalities Offsets Table: 0
    Nationalities Text Data Offset: 0
    Nationalities Text Data Size: 0

OVER Offsets:
    Stadiums Offsets Table 1: 0
    Stadiums Offsets Table 2: 0
    Leagues Offsets Table 1: 0
    Leagues Offsets Table 2: 0

Callnames:
    Name Lenght: 40
    Encoding: "cp932"
