MAIN_MENU_FILE_TEXT = "File"
MAIN_MENU_EDIT_TEXT = "Edit"
MAIN_MENU_HELP_TEXT = "Help"

FILE_MENU_OPEN_EXECUTABLE_TEXT = "Open SLXX/EBOOT.OLD"
FILE_MENU_OPEN_OVER_TEXT = "Open OVER"
FILE_MENU_OPEN_CALLNAME_TEXT = "Open Callname File"
FILE_MENU_SAVE_EXECUTABLE_TEXT = "Save SLXX/EBOOT.OLD"
FILE_MENU_SAVE_OVER_TEXT = "Save OVER"
FILE_MENU_SAVE_CALLNAME_TEXT = "Save Callname File"
FILE_MENU_EXIT_TEXT = "Exit"

EDIT_MENU_GAME_VER_TEXT = "Game Version"

HELP_MENU_MANUAL_TEXT = "Manual"
HELP_MENU_ABOUT_TEXT = "About"

APP_NAME = "PES/WE/JL Text Editor"